### ISSUE TITLE
Move 'bBox.txt' params into 'config-example.js' file

### ISSUE THREAD

**Issue by vlauciani** [INGV/shakemap4-web#51]
Hi Dario

Could you move the `bBox.txt` params into `config-example.js` file?

Thank you,
Valentino

**Comment by serioca** [comment]
The config.js file contains javascript code while the bBox.txt is a json encoded file and is read by a python script (on the server side).
I chose javascript rather than json after reading the following [article](https://medium.com/trabe/stop-using-json-config-files-ab9bc55d82fa)
In order to integrate bBox data it needs to move the config.js to json format.
Before to go on with the modification I want to make some question that can help me to understand some aspects of the application:
Does It have sense to make the bBox info read by the client side,  which could use them as parameters of  a web service call?

**Comment by amichelini** [comment]
If I understand it correctly, @serioca  you would like that the client decides which area to use. In other words, the user decides the area of the shakemaps. If this is so, the answer is no. It should be the service provider that decides which area the shakemaps are produced.  Please correct me.
@vlauciani @djozinovi

**Comment by vlauciani** [comment]
@serioca I understand your point regarding `config.js` and `bBox.txt`; I didn't know this thing. 

I agree with Alberto, the user doesn't decide the area of the ShakeMap.

An idea could be to convert the Javascript file into JSON file and update the webpage to get and parse the JSON to set params. 

What do you think about? Please, contact me as you like (Slack or face to face).

**Comment by djozinovi** [comment]
Hi All,

I think that by client side Sergio means that the processing of determining if the event is inside the bBox area will be done by the user's browser. From my perspective I think it's better that it's done server side, as it can slow down the loading of the page to the user if there are shakemaps of many events (which would the user's browser process). 

Dario

**Comment by vlauciani** [comment]
Yes, @djozinovi I agree with you...

**Comment by serioca** [comment]
Ok! Thanks!

**Comment by amichelini** [comment]
I agree with Dario. The shakemaps all done on the server and made available

**Comment by vlauciani** [comment]
Ok, nothing to do here.

close
